### PR TITLE
Archived existing slides

### PR DESCRIPTION
**Pull request by ElijahCaine**
Old slides are archived so we are encouraged to actually create new content instead of tweaking older content. We can still lift material from our old classes, but we should keep in mind that classes are shorter and so lessons should also be shorter.

Also updated localbuild.sh to specify using python2 (instead of defaulting to whatever python you use, which might break things on python3)

Who will do what slides for which weeks:

*Format: Topic | Who*

**Fall term:**
     
* Python + Programming | Lucy
* Web Frameworks | Eli
* Testing and CI | Tschuy
* Security | Lucy
* Databases | Tschuy
* Debuggers | Eli
* Contributing to OS | Lucy
* Review | Lucy

**Winter term:**

* Linux Basics and IRC | Lucy
* VCS and Editors | Eli
* Single System Fundamentals | Lucy
* Networking and DNS | Eli
* Security | Lucy
* Configuration Management | Lucy
* Configuration Management | Eli
* Docker and Environments | Eli
* Cloud Infrastructure | Lucy

@tschuy @lucywyman

### CODE REVIEW

**Comment by lucywyman** [comment]
@ElijahCaine  Why is this marked as do not merge again?  I rebased off of current master, and everything should (in theory) be up to date.

**Comment by dspt** [comment]
@lucywyman Removal of the curriculum page is the only thing I have to comment about.  Is that going to get replaced or just have the info elsewhere?

**Comment by lucywyman** [comment]
@dspt  I think there's a better solution than this, but I'll keep thinking about what that might be -- I made an archived videos page and put it under the "archive" section, moved that out to be a top-level menu item, and created a current videos page. 

Problems I see:
1. This isn't very elegant or easy to navigate if you're new to the site.
2. The word videos makes me think of VHS tapes or something, but "recordings" doesn't sound right either -- better word?

Neither of those seems prohibitive for merging the PR though.

**Comment by dspt** [comment]
I think saying Videos is fine.  If you'd like to do without the Curriculum page, we could just link to the videos from the slides.

**Comment by lucywyman** [comment]
Well, I think having the videos be their own page is valuable, but maybe it won't get much traffic?

**Comment by ElijahCaine** [comment]
@lucywyman I marked it as "DO NOT MERGE" because I wanted us to get updated slides for at least the first lesson or two merged in with this PR. As it stands (unless things changed) all slides are still in the archived directory and there's no current slides content (for the DOBC lessons, day-camp should still be good).

**Comment by lucywyman** [comment]
Ah, ok -- I assumed that updated slides would be a separate PR.

**Comment by ElijahCaine** [comment]
@lucywyman If you want to do that then I'm okay with making it a seperate PR. I just didn't want to make a massive change that might leave students confused looking around for the slides.

**Pull request merged**
