### PR TITLE
Add youtube playlists for videos page

### PR DESCRIPTION
**Pull request by lucywyman**
* I created playlists on youtube for each year of DOBC
* Link to those from Archived Videos page instead of each on individually
* Modify toctree so it's not a huge list of all the slides
* Make donate link on front page work

### CODE REVIEW

**Comment by ElijahCaine** [comment]
Is there a reason these aren't just being added to the already existing ``source/videos.rst`` ?

**Comment by lucywyman** [comment]
Oh, uh....I forgot?

**Comment by ElijahCaine** [comment]
@lucywyman Okay, it's nbd. I was just curious if you were putting old videos with the archived and would put newer videos in the 'Videos' page.
It'd make more sense to put recordings on the 'Videos' page, right now they're kinda hard to find from the main page.

Everything else looks good to me :smile:

**Comment by lucywyman** [comment]
@ElijahCaine done did

**Comment by ElijahCaine** [comment]
lgtm :+1:

**Pull request merged**
